In [1]:
import pandas as pd

In [2]:
kaggle_metadata=pd.read_csv('movies_metadata.csv', low_memory=False)
ratings=pd.read_csv('ratings.csv')

In [3]:
kaggle_metadata.sample(n=5)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
17871,False,NaN,0,[],NaN,41822,tt0099927,cn,客途秋恨,"Set in the early 1970s, it tells the story of ...",...,1990-04-27,0.0,100.0,"[{'iso_639_1': 'cn', 'name': '广州话 / 廣州話'}, {'i...",Rumored,NaN,Song of the Exile,False,5.0,1.0
26314,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",NaN,122192,tt1946298,fr,Le Guetteur,A major police operation to take down a notori...,...,2012-09-05,0.0,89.0,"[{'iso_639_1': 'fr', 'name': 'Français'}]",Released,NaN,The Lookout,False,5.5,34.0
3960,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",NaN,11028,tt0092654,en,The Big Easy,Remy McSwain is a New Orleans police lieutenan...,...,1986-11-27,0.0,102.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,A cop and a lady lawyer caught in an explosive...,The Big Easy,False,6.2,52.0
4960,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,19562,tt0070354,fr,Le Magnifique,François Merlin (Belmondo) is a Jean Bruce typ...,...,1973-11-23,0.0,95.0,"[{'iso_639_1': 'sq', 'name': 'shqip'}, {'iso_6...",Released,NaN,The Magnificent One,False,7.2,33.0
10862,False,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",NaN,35555,tt0436864,en,Unknown White Male,The true story of Doug Bruce who woke up on Co...,...,2005-06-01,0.0,88.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Unknown White Male,False,6.5,5.0

In [4]:
ratings.sample(n=5)

          userId  movieId  rating   timestamp
3234062    33631     1284     5.0   939030853
9294990    95957    31696     3.0  1238198101
14506119  150781    80363     2.0  1392902538
8826361    90994      926     5.0  1338004806
12188916  126438      597     5.0   833440166